#pragma once

bool RfidStart();
void RfidEnd();
void processRfidCard();
bool readUart(Stream& SerialPort);
void executeCommand();
void setMode();
void setTime();
void resetStation();
void getStatus();
void initChip();
void getLastTeams();
void getTeamRecord();
void readCardPages();
void updateTeamMask();
void writeCardPage();
void readFlash();
void writeFlash();
void eraseTeamFlash();
void getConfig();
void setVCoeff();
void setGain();
void setChipType();
void setTeamFlashSize();
void BTConfirmRequestCallback(uint32_t numVal);
void BTAuthCompleteCallback(boolean success);
void setBtName();
void setBatteryLimit();
void scanTeams();
void getLastErrors();
void setAutoReport();
void setAuth();
void setAuthPwd();
void setAuthPack();
void unlockChip();
void saveNewMask();
void clearNewMask();
uint16_t getBatteryLevel();
void beep(uint8_t, uint16_t);
void errorBeepMs(uint8_t, uint16_t);
void errorBeep(uint8_t);
void init_package(uint8_t);
bool addData(uint8_t);
void sendData();
bool ntagAuth(uint8_t* pass, uint8_t* pack, bool ignorePack);
bool ntagWritePage(uint8_t*, uint8_t, bool verify, bool forceNoAuth = false);
bool ntagRead4pages(uint8_t);
bool ntagSetPassword(uint8_t* pass, uint8_t* pack, bool noAuth, bool readAndWrite = false, uint8_t authlim = 0, uint8_t startPage = 0);
bool ntagRemovePassword(uint8_t* pass, uint8_t* pack, bool noAuth, bool readAndWrite = false, uint8_t authlim = 0, uint8_t startPage = 0);
bool writeCheckPointToCard(uint8_t, uint32_t);
int findNewPage();
bool checkTeamExists(uint16_t teamNumber);
bool writeDumpToFlash(uint16_t, uint32_t, uint32_t, uint16_t);
bool eraseTeamFromFlash(uint16_t);
bool readTeamFromFlash(uint16_t);
uint16_t refreshChipCounter();
void sendError(uint8_t, uint8_t);
void sendError(uint8_t);
void addLastTeam(uint16_t, bool);
void addLastError(uint8_t);
uint8_t crcCalc(uint8_t*, uint16_t, uint16_t);
void floatToByte(uint8_t*, float);
bool selectChipType(uint8_t);
void checkBatteryLevel();
void checkClockIsRunning();
void init_buzzer_pin(uint8_t buzzerPin);
void set_output(uint8_t pin, int outValue);
void esp32Tone(uint8_t pwmChannelNum, uint32_t freq);
void esp32NoTone(uint8_t pwmChannelNum);
