name: Setup Build Environment
description: Installs arduino-cli, platform core and libraries.

inputs:
  vendor:
    description: Arduino platform core to install (e.g., esp32)
    required: true
  architecture:
    description: 
    required: true
  board-id:
    description:
    required: true

env:
  CONFIG_PATH: ./BTStation_ESP32/arduino_cli.yaml
  LIBRARIES_PATH: ./BTStation_ESP32/libs/description.txt
  ZIP_LIBRARIES_PATH: ./BTStation_ESP32/libs_custom/description.txt

runs:
  using: composite
  steps:
    - name: Setup Arduino CLI
      uses: arduino/setup-arduino-cli@v2
      with:
        version: "1.1.1"

    - name: Install platform
      shell: bash
      run: |
        arduino-cli core update-index --config-file env.CONFIG_PATH
        arduino-cli core install --config-file "$CONFIG_PATH" "${{ inputs.vendor }}:${{ inputs.architecture }}"

    - name: Install libraries from web
      shell: bash
      run: |
        if [ ! -f "$LIBRARIES_PATH" ]; then
          echo "No $LIBRARIES_PATH found"
          exit 1
        fi
        xargs -a "$LIBRARIES_PATH" -r -I {} sh -c 'arduino-cli lib install --config-file '"$CONFIG_PATH"' "{}"'

    - name: Install libraries from zip
      shell: bash
      run: |
        if [ ! -f "$ZIP_LIBRARIES_PATH" ]; then
          echo "No $ZIP_LIBRARIES_PATH found"
          exit 1
        fi
        xargs -a "$ZIP_LIBRARIES_PATH" -r -I {} sh -c 'arduino-cli lib install --config-file '"$CONFIG_PATH"' "{}"'

    - name: Cache Environment
      uses: actions/cache@v4
      with:
        path: |
          ~/.arduino
        key: arduino-${{ inputs.vendor }}-${{ inputs.architecture }}-${{ hashFiles(env.LIBRARIES_PATH, env.ZIP_LIBRARIES_PATH)}}
