name: Setup Build Environment
description: Installs arduino-cli, platform core and libraries.

inputs:
  vendor:
    description: Arduino platform core to install (e.g., esp32)
    required: true
  architecture:
    description: 
    required: true
  board-id:
    description:
    required: true

env:
  CONFIG_PATH: ./BTStation_ESP32/arduino_cli.yaml
  LIBRARIES_DESCRIPTION_PATH: ./BTStation_ESP32/libs/description.txt
  ZIP_LIBRARIES_PATH: ./BTStation_ESP32/libs_custom
  ZIP_LIBRARIES_DESCRIPTION_PATH: ./BTStation_ESP32/libs_custom/description.txt

runs:
  using: composite
  steps:
    - name: Setup Arduino CLI
      uses: arduino/setup-arduino-cli@v2.0.0

    - name: Cache Environment
      id: arduino-cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.arduino
        key: arduino-${{ inputs.vendor }}-${{ inputs.architecture }}-${{ hashFiles(env.LIBRARIES_PATH, env.ZIP_LIBRARIES_PATH)}}

    - name: Install platform and libraries
      if: steps.arduino-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        arduino-cli core update-index --config-file "env.CONFIG_PATH"
        arduino-cli core install --config-file "env.CONFIG_PATH" "${{ inputs.vendor }}:${{ inputs.architecture }}"

        if [ ! -f "env.LIBRARIES_PATH" ]; then
          echo "No file for libraries found"
          exit 1
        fi
        xargs -a "env.LIBRARIES_PATH" -r -I {} sh -c 'arduino-cli lib install --config-file '"env.CONFIG_PATH"' "{}"'

        if [ ! -f "env.ZIP_LIBRARIES_PATH" ]; then
          echo "No file for zip libraries found"
          exit 1
        fi
        xargs -a "env.ZIP_LIBRARIES_PATH" -r -I {} sh -c 'arduino-cli lib install --config-file '"env.CONFIG_PATH"' --zip-path "env.ZIP_LIBRARIES_PATH/{}.zip"'