name: Firmware Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    strategy:
      matrix:
        sketch-profile: [default]
        rfid: [pn532, mfrc522]
        environment: [debug, production]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Compile Sketch
        env:
          PROJECT_DIR: ./BTStation_ESP32
          PROFILE: ${{ matrix.sketch-profile }}
          CONFIG_PATH: ./BTStation_ESP32/arduino_cli.yaml

          # Convert matrix.environment into -D flag
          EXTRA_FLAGS: >-
            ${{ matrix.environment == 'debug' && '-DDEBUG' || '' }}
            ${{ matrix.rfid == 'pn532' && '-DUSE_PN532' || '' }}
            ${{ matrix.rfid == 'mfrc522' && '-DUSE_MFRC522' || '' }}

        run: ./bin/common/build_firmware.sh